---
services:
  web:
    restart: always
    image: dalibo/explain.dalibo.com:latest
    ports:
      - "5001:5000"
    links:
      - postgres:postgres
    volumes:
      - .:/app
    environment:
      DEBUG_TB_PROFILER_ENABLED: true
      DB_SERVICE: postgres
      SQLALCHEMY_DATABASE_URI: postgresql+psycopg2://postgres:postgres@postgres:5432/postgres

  postgres:
    restart: always
    image: postgres:latest
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    environment:
      POSTGRES_PASSWORD: postgres

volumes:
  db-data:
